# Generated by Django 5.0.6 on 2024-07-15 16:33

import froala_editor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_note_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='body',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
    ]
