# Generated by Django 5.0.6 on 2024-07-21 10:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_note_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='child_notes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='note',
            name='is_head_note',
            field=models.BooleanField(default=False),
        ),
    ]
