# Generated by Django 5.0.6 on 2024-08-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_note_priority_alter_tag_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=400, unique=True),
        ),
    ]
