# Generated by Django 5.0.6 on 2024-08-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
